### ISSUE TITLE
 X8318S/9235 motor model

### ISSUE THREAD

**Issue by solomondg** [G-Levine/OpenTorque-Actuator#3]
Hey there! Maybe I'm just totally incompetent, but I haven't been able to find a model out there for 9235 class brushless motors. Seems there's one present in a lot of the renders - if you're at liberty to share it, would you mind popping it into the repo and saving us the trouble of modeling it ourselves?

Thanks a ton!

**Comment by G-Levine** [comment]
Hi,
I didn't make the model for the 9235 motor shown in the pictures; it's borrowed from Robin Frojd's RFX gearbox (https://hackaday.io/project/162387-rfx-gearbox). You can download his STEP file to get the motor model.

**Comment by solomondg** [comment]
Oh wow, thank you so much! Appreciate the link :)
