### ISSUE TITLE
Cheaper Bearing?

### ISSUE THREAD

**Issue by IpsumDominum** [G-Levine/OpenTorque-Actuator#4]
Hey :)
I am a very beginner,
It seems like the https://www.alibaba.com/product-detail/RA8008-crossed-roller-bearing-THK-bearing_1912942608.html bearing from alibaba is quite high priced.. What would be an alternative?

Thanks!
C Lu

**Comment by rohanbaba** [comment]
Try searching for 61816-ZZ and you will find it in your local stores online. (eg. https://www.bearingrevolution.co.uk/61816-zz-60330)
This is a relatively very common type of bearing as well as very cheap with similar dimensions.
To use this bearing in the assembly, you will need to slightly tweak some dimensions of its housing.

**Comment by STGRobotics** [comment]
https://www.amazon.com/Ochoos-80x100x10mm-Precision-Groove-Bearings/dp/B07R5Q6BBB/ref=sr_1_1?dchild=1&keywords=61816+ZZ&qid=1614945251&sr=8-1

https://www.astbearings.com/catalog/thin_section_metric?filter=a01_bore_dia_mm%3A2%3A80.0%3Ba02_outer_dia_mm%3A2%3A100.0#cds-attribute-a02_outer_dia_mm

**Comment by IpsumDominum** [comment]
Thanks very much!
